// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PruebaRedarbor.Infrastruture;
using System;
using System.Collections.Generic;
using PruebaRedarbor.Domain.Models;


#nullable disable

namespace PruebaRedarbor.Infrastruture.Configurations
{
    public partial class CompaniesConfiguration : IEntityTypeConfiguration<Companies>
    {
        public void Configure(EntityTypeBuilder<Companies> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Companie__3214EC076A0FEEEE");

            entity.Property(e => e.Name).HasMaxLength(255);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Companies> entity);
    }
}
