// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PruebaRedarbor.Infrastruture;
using System;
using System.Collections.Generic;
using PruebaRedarbor.Domain.Models;


#nullable disable

namespace PruebaRedarbor.Infrastruture.Configurations
{
    public partial class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC0728DBC5D1");

            entity.Property(e => e.CreatedOn)
            .HasDefaultValueSql("(getdate())")
            .HasColumnType("datetime");
            entity.Property(e => e.DeletedOn).HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(255);
            entity.Property(e => e.Fax).HasMaxLength(50);
            entity.Property(e => e.LastLogin).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(255);
            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.Telephone).HasMaxLength(50);
            entity.Property(e => e.UpdatedOn).HasColumnType("datetime");

            entity.HasOne(d => d.Company).WithMany(p => p.Employee)
            .HasForeignKey(d => d.CompanyId)
            .HasConstraintName("FK_Users_Companies");

            entity.HasOne(d => d.Role).WithMany(p => p.Employee)
            .HasForeignKey(d => d.RoleId)
            .HasConstraintName("FK_Users_Roles");

            entity.HasOne(d => d.Status).WithMany(p => p.Employee)
            .HasForeignKey(d => d.StatusId)
            .HasConstraintName("FK_Users_Status");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Employee> entity);
    }
}
