// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PruebaRedarbor.Infrastruture;
using System;
using System.Collections.Generic;
using PruebaRedarbor.Domain.Models;


#nullable disable

namespace PruebaRedarbor.Infrastruture.Configurations
{
    public partial class RolesConfiguration : IEntityTypeConfiguration<Roles>
    {
        public void Configure(EntityTypeBuilder<Roles> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK__Roles__3214EC071077F067");

            entity.Property(e => e.Name).HasMaxLength(100);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Roles> entity);
    }
}
